name: Mosers tests


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select test to run
        required: true
        type: choice
        default: all
        options:
          - account
          - ecofriendly
          - sales
          - startpage
          - regression
          - all

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    name: Run autotests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependancies
        run: pip install -r requirements.txt
      - name: run account tests
        if: "github.event.inputs.deployment_target == 'account'"
        run: cd tests && pytest -m smoke -v -s --alluredir=allure-results
        continue-on-error: true
      - name: run ecofriendly tests
        if: "github.event.inputs.deployment_target == 'ecofriendly'"
        run: cd tests && pytest -m smoke -v -s --alluredir=allure-results
        continue-on-error: true
      - name: run sales tests
        if: "github.event.inputs.deployment_target == 'sales'"
        run: cd tests && pytest -m smoke -v -s --alluredir=allure-results
        continue-on-error: true
      - name: run startpage tests
        if: "github.event.inputs.deployment_target == 'startpage'"
        run: cd tests && pytest -m smoke -v -s --alluredir=allure-results
        continue-on-error: true
      - name: run regression tests
        run: cd tests && pytest -m regression -v -s --alluredir=allure-results
        if: "github.event.inputs.deployment_target == 'regression'"
        continue-on-error: true
      - name: run all tests
        run: cd ui_tests_eokulik && pytest -v -s --alluredir=allure-results
        if: "github.event.inputs.deployment_target == 'all'"
        continue-on-error: true
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.28.0/allure-2.28.0.tgz && 
          sudo tar -zxvf allure-2.28.0.tgz -C /opt/ &&
          sudo ln -s /opt/allure-2.28.0/bin/allure /usr/bin/allure
      - name: generate report
        run: allure generate -c tests/allure-results -o _site
      - name: Save report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 1
      
  publish-report:
    name: Report publication
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
